### ISSUE TITLE
Error "Try signing in with a different account"

### ISSUE THREAD

**Issue by shiqocred** [dejwid/ecommerce-admin#1]
<img width="1440" alt="Jepretan Layar 2023-04-21 pukul 16 37 21" src="https://user-images.githubusercontent.com/90097870/233603359-73dcc994-38cd-42ba-ab1f-5d28718c6aaf.png">
<img width="1440" alt="Jepretan Layar 2023-04-21 pukul 16 37 36" src="https://user-images.githubusercontent.com/90097870/233603389-136d7ec5-b2a6-400e-a912-ecdded1dcd8b.png">
<img width="1440" alt="Jepretan Layar 2023-04-21 pukul 16 37 44" src="https://user-images.githubusercontent.com/90097870/233603403-78129578-4bc1-4231-88e5-17503f0bd654.png">
<img width="1194" alt="Jepretan Layar 2023-04-21 pukul 16 38 05" src="https://user-images.githubusercontent.com/90097870/233603410-92e3df42-3591-4524-b581-86d7a2f5efe1.png">

that normally until I add mongoDBAdapter

**Comment by Debanjan10** [comment]
I am also having the same problem, if you find any solution please update. Thank you. I checked that the ip address is also same with mongodb.but eventually the problem remains

**Comment by giacomolucalorusso** [comment]
I am having same problem too.
Any solution?

**Comment by sanyam-sindhu** [comment]
@shiqocred issue is that MongoDB is not establishing the connection .Try adding out current IP address to the database access or set it to 0.0.0.0 to any IP .
If this doesnt solve your problem Try changing the .env file to this format 
NEXTAUTH_URL=http://localhost:3000
SECRET=sanyam_sindhu_is_key //random secret key
GOOGLE_ID="xxxxxxxxx"
GOOGLE_SECRET="xxxxxxxxxxxx"
MONGODB_URI="xxxxxxxxxxx"

**Comment by Debanjan10** [comment]
Yeah, actually found out this exact solution to give global access to mongodb while building another project. set the ip address to 0.0.0.0/0

**Comment by ggkmkomega** [comment]
hey guys i tried the same thing and didnt work
any solutions?
